snc_redis:
    clients:
        default:
            type: predis
            alias: default
            logging: false
            dsn: '%env(REDIS_URL)%'
            options:
                connection_timeout: 5