rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php bin/console baldinof:roadrunner:worker"

http:
  address: 0.0.0.0:8080
  max_request_size: 64
  middleware: [ "gzip" ]
  uploads:
    forbid: [ ".php", ".exe", ".bat" ]
  static:
    dir: "public"
    allow: [ ".php" ]
  pool:
    num_workers: 4

status:
  address: localhost:2114

logs:
  mode: production
  channels:
    http:
      level: info # Log all http requests, set to info to disable
    server:
      level: info # Everything written to worker stderr is logged
      mode: raw
    metrics:
      level: info
